### ISSUE TITLE
event并发支持

### ISSUE THREAD

**Issue by lr874355227** [goravel/framework#1]
如果是并发场景下，注册事件时，这个listener能否支持匿名函数呢，并发场景下需要返回一个新的listener对象，比方说这样
func (receiver *EventServiceProvider) listen() map[events.Event][]events.Listener {
	return map[events.Event][]events.Listener{
		&events.TestEvent{}: {
			func() events.Listener {
				return &listeners.TestListener{}
			},
		},
	}
}

**Comment by hwbrzzl** [comment]
抱歉，上周休假了，刚看到。

如果 listener 不使用 queue，目前同一个 event 下的 listener 是线性执行的，当某一个 listener 返回 error，即结束后续 listener。
如果 listener 使用 queue，则进行异步执行。

对你说的并发场景，我不是很理解，可否举个例子，详细说明下~

**Comment by hwbrzzl** [comment]
我先关闭了，有需要请重新打开。
