### ISSUE TITLE
Implement IoC Container for Goravel Framework

### ISSUE THREAD

**Issue by anabeto93** [goravel/framework#100]
## Description of Problem
Currently, the Goravel framework does not provide a built-in inversion of control (IoC) container like Laravel does. Implementing an IoC container would make dependency management easier and more flexible for developers using Goravel.

## Proposed Solution
Create a new package within the Goravel framework to implement an IoC container. The container should support features such as:
1. Contracts/interfaces for both `Container` and `Application`. Would enable having `$this->app` (in Laravel) in goravel.
2. Registering and resolving dependencies.
3. Support for singleton instances.
4. Handling aliases for registered dependencies.
5. Optional support for automatic resolution of constructor dependencies (similar to Laravel).

#### Note
As previously mentioned, having this would enable passing the `*foundation.Application` to service providers that implement `contracts.ServiceProvider`

### Basic Example Implementation
The actual `Container` would be more complex than this but this is simply to provide more context. Inspiration is taken from `Illuminate\Contracts\Container` and its implementation in `Illuminate\Container`
```go
package support

import (
	"errors"
	"sync"
)

type Container struct {
	Bindings sync.Map
}

func (c *Container) Bind(key string, value interface{}) {
	c.Bindings.Store(key, value)
}

func (c *Container) Resolve(key string) (interface{}, error) {
	value, ok := c.Bindings.Load(key)
	if !ok {
		return nil, errors.New("binding not found")
	}
	return value, nil
}

```

## Additional Context
Inclusion of an IoC container would bring Goravel closer to parity with Laravel's features and provide a more familiar environment for developers coming from Laravel/PHP backgrounds. This would make the framework more appealing to a wider range of developers and potentially increase its adoption.

This is also supposed to help in [#49](https://github.com/goravel/goravel/issues/49)

**Comment by hwbrzzl** [comment]
Yes, thanks, good idea, we have some discussions on this function before, the key point is how to solve the problem of assertion.

The `Resolve` method in your example returns `interface{}`, how do we change the `interface{}` to a specify type?

**Comment by hwbrzzl** [comment]
Emm, how can we get `ExpectedStructType` in framework? `resolvedInstance` maybe comes from a third package, right?

**Comment by anabeto93** [comment]
Assuming we had something like this 
```go
type binding struct {
    concrete interface{}
    shared   bool
}

type Container struct {
    bindings                       map[string]*binding
    instances                      map[string]interface{}
    aliases                        map[string]string
}
```

so that when you request to `container.Resolve()`, it would return something from either instances or aliases. Even though the return type of `Resolve()` is `interface{}`, it would actually be returning what you previously aliased through `container.Alias()`. Resolving an instance will require first binding (`.Bind()`), aliasing (`.Alias()`), or extending (`.Extend()`) in order to be able to resolve it later on. The framework will only be keeping a `map[string]interface{}` of everything registered, so when you need it, it'll return it to you.

Regarding `ExpectedStructType`, when resolving instances from third-party packages, you can use Golang's reflection package to determine the specific type of the interface being resolved. You can then cast the returned `interface{}` from `container.Resolve()` to the appropriate type before using it in your application. This way, you can ensure type safety while working with instances from various packages.

Inspiration for this is coming from 
```php
class Container implements ArrayAccess, ContainerContract
```
in Laravel `namespace Illuminate\Container;`

**Comment by anabeto93** [comment]
I also just want to note that, being able to `bind()` and `resolve()` interfaces would require having a single instance of the `*foundation.Application` or `*container.Container` being available to all service providers and other `structs` (or classes) including `Facades` during a request lifecycle. Additionally, we would also need `sync.RWMutex` for concurrency sake since golang is not like PHP.

Using a `sync.RWMutex` in the `container.Container` implementation would help ensure that the container behaves correctly when multiple goroutines access it concurrently.For the sake of multiple requests being processed in parallel.

**Comment by anabeto93** [comment]
Hi @hwbrzzl I'm currently trying something out in the meantime and just wanted to share this snippet of how I am using the `Container` to resolve an interface to a specific type, in this case `config.Cache` which would resolve to `facades.Config` 

```go
package foundation

import (
	"errors"
	"github.com/goravel/framework/contracts/config"
	containercontract "github.com/goravel/framework/contracts/container"
	"reflect"
	"strings"
	"sync"
)

type BaseManager struct {
	app            containercontract.Container
	config         config.Config
	drivers        map[string]interface{}
	customCreators map[string]func() interface{}
	mu             sync.RWMutex
}

func NewBaseManager(app *Application) *BaseManager {
	configManager, err := app.Make("config")
	if err != nil {
		panic(err)
	}
	return &BaseManager{
		app:            app,
		config:	   configManager.(config.Config),
		drivers:       make(map[string]interface{}),
		customCreators: make(map[string]func() interface{}),
	}
}
```. I hope this helps my case. Trying my hands on something like this from Laravel
```php
<?php

namespace Illuminate\Support;

use Closure;
use Illuminate\Contracts\Container\Container;
use InvalidArgumentException;

abstract class Manager
{
    /**
     * The container instance.
     *
     * @var \Illuminate\Contracts\Container\Container
     */
    protected $container;

    /**
     * The configuration repository instance.
     *
     * @var \Illuminate\Contracts\Config\Repository
     */
    protected $config;

    /**
     * The registered custom driver creators.
     *
     * @var array
     */
    protected $customCreators = [];

    /**
     * The array of created "drivers".
     *
     * @var array
     */
    protected $drivers = [];

    /**
     * Create a new manager instance.
     *
     * @param  \Illuminate\Contracts\Container\Container  $container
     * @return void
     */
    public function __construct(Container $container)
    {
        $this->container = $container;
        $this->config = $container->make('config');
    }
```

**Comment by hwbrzzl** [comment]
Thanks for your example, I also wrote one, PTAL.

```go
// Define Container
type Container struct {
	Bindings sync.Map
}

func (c *Container) Bind(key any, value any) {
	c.Bindings.Store(key, value)
}

func (c *Container) Make(key any) (any, error) {
	binding, ok := c.Bindings.Load(key)
	if !ok {
		return nil, errors.New("binding not found")
	}

	return binding, nil
}

func (c *Container) MakeFacade(facade contracts.Facade) error {
	binding, ok := c.Bindings.Load(facade.GetFacadeAccessor())
	if !ok {
		return errors.New("binding not found")
	}

	return facade.ResolveFacadeInstance(binding)
}

// Define Facade interface
type Facade interface {
	GetFacadeAccessor() string
	ResolveFacadeInstance(instance any) error
}

// Define facades.Sms
var Sms = &SmsImpl{}

type SmsImpl struct {
	sms.Sms
}

func (receiver *SmsImpl) GetFacadeAccessor() string {
	return "sms"
}

func (receiver *SmsImpl) ResolveFacadeInstance(instance any) error {
	if sms, ok := instance.(sms.Sms); ok {
		receiver.Sms = sms

		return nil
	}

	return errors.New("not implement github.com/goravel/framework/contracts/sms")
}

// Define Sms implementation
type Sms struct {
}

func (s *Sms) Send() bool {
	fmt.Println("Send")

	return false
}

// Test
func TestSms(t *testing.T) {
	container := new(Container)
	container.Bind("sms", &Sms{})
	_ = container.MakeFacade(facades.Sms)

	facades.Sms.Send()
}
```

**Comment by anabeto93** [comment]
Hi @hwbrzzl I think I remember seeing something like this somewhere. Funny enough I can't seem to find it now either in `goravel/goravel` or `goravel/framework`. I'm trying to follow this approach so that we can bind and resolve interfaces. I encountered a situation that got me thinking about the very first question you asked, imagine we are dealing with Fakers, or multiple implementations of an interface, and we have to resolve to one based on condition like in `AppServiceProvider` then what happens right? :smile:

**Comment by hwbrzzl** [comment]
Yes, we must know how to assert. Just like `ResolveFacadeInstance(instance any) error` in `Facade interface`.

**Comment by hwbrzzl** [comment]
Hi @anabeto93 Just wonder if you are still working on this issue? If not, I'll do something about it.

**Comment by anabeto93** [comment]
I have a `container.Container` struct implementation of this interface
```go
package container

type Container interface {
	Bound(abstract string) bool
	Alias(abstract string, alias string) error
	Tag(abstracts interface{}, tags ...interface{}) error
	Tagged(tag string) (map[string]interface{}, error)
	Bind(abstract string, concrete interface{}, shared bool) error
	BindIf(abstract string, concrete interface{}, shared bool) error
	Singleton(abstract string, concrete interface{}) error
	SingletonIf(abstract string, concrete interface{}) error
	Scoped(abstract string, concrete interface{}) error
	ScopedIf(abstract string, concrete interface{}) error
	Extend(abstract string, closure func(...interface{}) (interface{}, error)) error
	Instance(abstract string, instance interface{}) (interface{}, error)
	ForgetInstance(abstract string)
	AddContextualBinding(concrete string, abstract string, implementation interface{}) error
	When(concrete ...interface{}) ContextualBindingBuilder
	Factory(abstract string) func() (interface{}, error)
	Flush() error
	Make(abstract string, parameters ...interface{}) (interface{}, error)
	Call(callback interface{}, parameters ...interface{}) (interface{}, error)
	Resolve(abstract string, raiseEvents bool, parameters ...interface{}) (interface{}, error)
	Resolved(abstract string) bool
	BeforeResolving(abstract interface{}, callback *func(string, Container, ...interface{}) error) error
	Resolving(abstract interface{}, callback *func(string, Container, ...interface{}) error) error
	AfterResolving(abstract interface{}, callback *func(string, Container, ...interface{}) error) error
	IsInstance(abstract string) bool
}
```
which follows the `\Illuminate\Contracts\Container\Container::class` interface from Laravel. The only challenge now is the `foundation.Application` which is introducing a couple of breaking changes to it. It seems a whole lot more complex once I make `foundation.Application` to compose/extend `container.Container`

![image](https://user-images.githubusercontent.com/7607657/235695613-6bfdfbfe-1600-4e83-8584-9f2a0aa36651.png)

**Comment by hwbrzzl** [comment]
I think we don't need so many methods at the beginning, just implementing the main logic is ok.

**Comment by hwbrzzl** [comment]
We can move our discussion to https://github.com/goravel/goravel/issues/120.

**Comment by hwbrzzl** [comment]
Hi @anabeto93 I created a PR for this issue, PTAL, we can have an in-depth discussion on this: https://github.com/goravel/goravel/pull/124
