### ISSUE TITLE
jwt鉴权支持非数字主键ID

### ISSUE THREAD

**Issue by Meaningisuse** [goravel/framework#17]
习惯使用uuid作为主键，目前通过token获取用户信息，用户表必须是数字主键，不然会报错

<img width="994" alt="image" src="https://user-images.githubusercontent.com/15310195/211159389-2b671e4b-0aa0-4361-9bb9-bf3d0680e837.png">

**Comment by hwbrzzl** [comment]
感谢 Issue，可否发一下 a_user 表的 struct 看一下。

**Comment by Meaningisuse** [comment]
```go
type AUser struct {
	AUid   string `gorm:"primaryKey"`
	AName  string
	Mobile string
	Salt   string
	Passwd string
	orm.Timestamps
}
```

**Comment by hwbrzzl** [comment]
修复了，请升级 v1.7.3 试一下，升级文档：https://www.goravel.dev/zh/upgrade/v1.7.html，如果有问题请随时沟通 ~
