### ISSUE TITLE
facades.Orm.Query.First() doesn't return ErrRecordNotFound

### ISSUE THREAD

**Issue by kcaashish** [goravel/framework#20]
I checked and found this in gorm.go:

```go
func (r *GormQuery) Find(dest interface{}, conds ...interface{}) error {
	return r.instance.Find(dest, conds...).Error
}

func (r *GormQuery) First(dest interface{}) error {
	err := r.instance.First(dest).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil
	}

	return err
}
```

Why is nil being returned in case of ErrRecordNotFound?

**Comment by hwbrzzl** [comment]
Hi, sorry for being late. 
Yes, `First` doesn't return ErrRecordNotFound, there are two reasons for this logic:
1. we want `Find` and `First` have a consistent return when no record is found;
2. `First`should't return an error when no record is found;
