### ISSUE TITLE
Can we add Make function to package stub?

### ISSUE THREAD

**Issue by kadirgun** [goravel/framework#648]
https://github.com/goravel/framework/blob/634b3a1e33432edda950502d3c54cf396239f9fd/foundation/console/package_make_command_stubs.go#L27-L51

```go
func Make() contracts.DummyCamelName {
	instance, err := App.Make(Binding)

	if err != nil {
		return nil
	}

	return instance.(contracts.DummyCamelName )
}
```

I'm not sure if this is a good idea. Is there an easier way to get service from within the app?

**Comment by hwbrzzl** [comment]
Yes, you can do it in your package.
