### ISSUE TITLE
添加Dependabot自动更新依赖

### ISSUE THREAD

**Issue by DevHaoZi** [goravel/framework#82]
目前框架内使用的三方包还是挺多的，也许可以考虑添加GitHub的Dependabot自动管理它们。

**Comment by DevHaoZi** [comment]
相关文档：[https://docs.github.com/zh/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file](https://docs.github.com/zh/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)

**Comment by hwbrzzl** [comment]
恩，有这个计划，还没有处理是因为考虑到目前单测覆盖率还不高，贸然升级怕有问题。

**Comment by DevHaoZi** [comment]
Will move to goravel.
